
## Rule engine for master plan ordering (category/action sequence)
plan.ordering.rules[0].category=SIDE
plan.ordering.rules[0].actions=NEW,UPDATE

plan.ordering.rules[1].category=TRANSACTION
plan.ordering.rules[1].actions=DELETE,UPDATE,NEW
plan.ordering.rules[1].sort-transaction-sequence=true

plan.ordering.rules[2].category=SIDE
plan.ordering.rules[2].actions=DELETE

plan.ordering.rules[3].category=CHART_OF_ACCOUNTS
plan.ordering.rules[3].actions=NEW,UPDATE,DELETE

plan.ordering.rules[4].category=ACCOUNT
plan.ordering.rules[4].actions=NEW,UPDATE,DELETE

plan.ordering.rules[5].category=DERIVED_PORTFOLIO
plan.ordering.rules[5].actions=NEW,UPDATE

plan.ordering.rules[6].category=PORTFOLIO_GROUP
plan.ordering.rules[6].actions=NEW,UPDATE,DELETE

plan.ordering.rules[7].category=DERIVED_PORTFOLIO
plan.ordering.rules[7].actions=DELETE
