
## Rule engine for master plan ordering (category/action sequence)
plan.ordering.rules[0].category=SIDE
plan.ordering.rules[0].actions=NEW,UPDATE

plan.ordering.rules[1].category=TRANSACTION
plan.ordering.rules[1].actions=DELETE,UPDATE,NEW
plan.ordering.rules[1].sort-transaction-sequence=true

plan.ordering.rules[2].category=SIDE
plan.ordering.rules[2].actions=DELETE

plan.ordering.rules[3].category=CHART_OF_ACCOUNTS
plan.ordering.rules[3].actions=NEW,UPDATE,DELETE

plan.ordering.rules[4].category=ACCOUNT
plan.ordering.rules[4].actions=NEW,UPDATE,DELETE

plan.ordering.rules[5].category=POSTING_RULE
plan.ordering.rules[5].actions=NEW,UPDATE,DELETE

plan.ordering.rules[6].category=ABOR_CONFIGURATION
plan.ordering.rules[6].actions=NEW,UPDATE,DELETE

plan.ordering.rules[7].category=ABOR
plan.ordering.rules[7].actions=NEW,UPDATE,DELETE

plan.ordering.rules[8].category=DERIVED_PORTFOLIO
plan.ordering.rules[8].actions=NEW,UPDATE

plan.ordering.rules[9].category=PORTFOLIO_GROUP
plan.ordering.rules[9].actions=NEW,UPDATE,DELETE

plan.ordering.rules[10].category=DERIVED_PORTFOLIO
plan.ordering.rules[10].actions=DELETE

# File locations
cacex.paths.changed-files-dir=changedfiles
cacex.paths.state-files-dir=statefiles
cacex.paths.plan-dir=plan
cacex.paths.master-plan-file=masterplan.json
