graph LR
ChangedFilesProvider --> PlanRunner
PlanRunner --> PlanService
PlanService --> PlanOrderingRuleEngine
PlanOrderingRuleEngine --> PlanWriter
PlanRunner --> PlanApplyService
PlanApplyService --> PlanItemApplier
PlanItemApplier --> PlanItemActionService
PlanItemActionService --> StateFileService
